version: '3.8'

services:
  backend:
    build: ./code/backend
    ports: 
      - "5000:5000"
    env_file:
      - ./code/backend/.env
    depends_on:
      - mongo
    networks:
      - bivacs-network
    volumes: 
      - ./code/backend:/app
      - /app/node_modules

  frontend:
    build: ./code/frontend-vue
    ports:
      - "5173:5173"
    # Forza Vite a esporre la porta al di fuori del container Docker
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend
    networks:
      - bivacs-network
    volumes:
      # Collega la cartella locale al container (Hot-Reload)
      - ./code/frontend-vue:/app
      # Protegge i node_modules
      - /app/node_modules

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    networks:
      - bivacs-network
    volumes:
      # Unico volume nominale vero e proprio, per salvare i dati del Database
      - bivacs_mongo-data:/data/db

networks:
  bivacs-network:
    driver: bridge

volumes:
  bivacs_mongo-data:
